"""SQL guardrails: block dangerous statements, require SELECT-only + LIMIT.

This is the authoritative safety layer. Every query — whether typed directly
against POST /api/validate-sql or generated by the LLM inside POST /api/query
— passes through `validate_sql` before it is ever allowed to reach a database
connection. Execution is additionally hardened in `database.py` (read-only
connections, a server/engine-level query timeout, and a hard row cap), so a
statement that somehow slipped past this layer would still be constrained.
"""
from __future__ import annotations

import sqlparse
from sqlparse import tokens as T

# Keywords that mutate data/schema, change privileges, or escape the current
# query (multi-statement smuggling, PRAGMA/ATTACH tricks, etc).
FORBIDDEN_KEYWORDS = {
    "DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "TRUNCATE", "CREATE",
    "GRANT", "REVOKE",
    # Defense in depth beyond the required list.
    "REPLACE", "MERGE", "ATTACH", "DETACH", "PRAGMA", "VACUUM", "REINDEX",
    "EXEC", "EXECUTE", "CALL", "COPY", "INTO",
}

ALLOWED_START = {"SELECT", "WITH"}


def validate_sql(sql: str) -> tuple[bool, str]:
    """Return (is_safe, reason).

    Safe means: exactly one statement, starting with SELECT/WITH, containing
    no forbidden keyword, and carrying a top-level LIMIT clause.
    """
    if not sql or not sql.strip():
        return False, "Empty SQL statement."

    statements = [s for s in sqlparse.parse(sql) if str(s).strip()]
    if not statements:
        return False, "No SQL statement found."
    if len(statements) > 1:
        return False, "Multiple statements are not allowed."

    statement = statements[0]

    first = _first_keyword(statement)
    if first is None:
        return False, "Could not determine statement type."
    if first.upper() not in ALLOWED_START:
        return False, f"Only SELECT/WITH queries are allowed, got '{first.upper()}'."

    has_limit = False
    depth = 0
    for token in statement.flatten():
        if token.ttype is T.Punctuation:
            if token.value == "(":
                depth += 1
            elif token.value == ")":
                depth -= 1
            continue
        if token.ttype in (T.Keyword, T.DML, T.DDL):
            word = token.value.upper()
            if word in FORBIDDEN_KEYWORDS:
                return False, f"Forbidden keyword: '{word}'."
            if word == "LIMIT" and depth == 0:
                has_limit = True

    if not has_limit:
        return False, "Query must include a top-level LIMIT clause."

    return True, "Query is a read-only SELECT with a LIMIT clause."


def has_top_level_limit(sql: str) -> bool:
    """True if the (single) statement in `sql` has a LIMIT outside any parens."""
    statements = [s for s in sqlparse.parse(sql) if str(s).strip()]
    if not statements:
        return False
    depth = 0
    for token in statements[0].flatten():
        if token.ttype is T.Punctuation:
            if token.value == "(":
                depth += 1
            elif token.value == ")":
                depth -= 1
            continue
        if depth == 0 and token.ttype is T.Keyword and token.value.upper() == "LIMIT":
            return True
    return False


def ensure_limit(sql: str, max_rows: int) -> str:
    """Append a `LIMIT max_rows` if the query doesn't already have one.

    Used on LLM-generated SQL so an otherwise-safe query isn't rejected just
    because the model forgot a LIMIT — the row cap in database.py enforces
    max rows regardless, this just makes the intent explicit in the SQL text.
    """
    cleaned = sql.strip().rstrip(";").rstrip()
    if has_top_level_limit(cleaned):
        return cleaned
    return f"{cleaned} LIMIT {max_rows}"


def _first_keyword(statement) -> str | None:
    for token in statement.flatten():
        if token.is_whitespace or token.ttype in T.Comment:
            continue
        if token.ttype in (T.DML, T.Keyword):
            return token.value
        return token.value
    return None
